# Generated by Django 4.2.1 on 2023-05-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealtyAd',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=4096)),
                ('title', models.CharField(blank=True, max_length=1024)),
            ],
        ),
    ]
