# Generated by Django 4.2.1 on 2023-05-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyad',
            name='city',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='realtyad',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realtyad',
            name='short_description',
            field=models.CharField(blank=True, max_length=8096),
        ),
        migrations.AddField(
            model_name='realtyad',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='realtyad',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
