# Generated by Django 4.2.1 on 2023-05-07 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_alter_realtyad_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyad',
            name='date_posted',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
