# Generated by Django 4.2.1 on 2023-05-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_realtyad_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=8096)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('filename', models.CharField(max_length=4096)),
            ],
        ),
        migrations.AddField(
            model_name='realtyad',
            name='address',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='realtyad',
            name='contacts',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='realtyad',
            name='long_description',
            field=models.TextField(blank=True, max_length=8096),
        ),
        migrations.AlterField(
            model_name='realtyad',
            name='url',
            field=models.CharField(max_length=8096),
        ),
        migrations.AddField(
            model_name='realtyad',
            name='images',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='realty.image'),
        ),
    ]
