# Generated by Django 4.2.1 on 2023-05-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_image_realtyad_address_realtyad_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyad',
            name='ad_id',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
