# Generated by Django 4.2.1 on 2023-05-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_realtyad_ad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
