# Generated by Django 4.2.1 on 2023-05-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0009_alter_realtyad_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtyad',
            name='images',
        ),
    ]
