# Generated by Django 4.2.1 on 2023-05-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0010_remove_realtyad_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyad',
            name='images',
            field=models.ManyToManyField(to='realty.image'),
        ),
    ]
