# Generated by Django 4.2.1 on 2023-05-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0011_realtyad_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.ImageField(default='noimage.jpg', upload_to='salesme_images'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnial',
            field=models.ImageField(default='noimage.jpg', upload_to='salesme_thumbnails'),
        ),
    ]
