# Generated by Django 4.2.1 on 2023-05-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0013_rename_thumbnial_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
    ]
