# Generated by Django 4.2.1 on 2023-05-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0014_remove_image_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
