# Generated by Django 4.2.1 on 2023-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0015_alter_image_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtyad',
            old_name='contacts',
            new_name='phones',
        ),
        migrations.AddField(
            model_name='realtyad',
            name='telegram',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='realtyad',
            name='viber',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='realtyad',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=8096),
        ),
    ]
