# Generated by Django 4.2.1 on 2023-05-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0016_rename_contacts_realtyad_phones_realtyad_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtyad',
            name='ad_author',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
